config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'index#index', as: :index
  post '/', to: 'index#post'

  get '/account-details', to: 'account_details#account_details', as: :account_details
  post '/account-details', to: 'account_details#post'

  get '/organisation', to: 'organisation#organisation', as: :organisation
  post '/organisation', to: 'organisation#post'
  
  get '/organisation_summary', to: 'organisation_summary#organisation_summary', as: :organisation_summary
  post '/organisation_summary', to: 'organisation_summary#post'

  get '/team', to: 'team#team', as: :team
  post '/team', to: 'team#post'

  get '/service', to: 'service#service', as: :service
  post '/service', to: 'service#post'

  get '/out-of-hours-support', to: 'out_of_hours_support#out_of_hours_support', as: :out_of_hours_support
  post '/out-of-hours-support', to: 'out_of_hours_support#post'

  get '/security', to: 'security#security', as: :security
  post '/security', to: 'security#post'

  get '/administrators', to: 'administrators#administrators', as: :administrators
  post '/administrators', to: 'administrators#post'

  get '/check-your-answers', to: 'check_your_answers#check_your_answers', as: :check_your_answers
  post '/check-your-answers', to: 'check_your_answers#post'

  get '/confirmation/account', to: 'confirmation#account', as: :confirmation_account

  get '/auth/google_oauth2/callback', to: 'google_auth#callback'
  get '/auth/google_oauth2/error/bad-email', to: 'google_auth#error_bad_email', as: :error_bad_email

  if Rails.env.development?
    get '/dev-login' => 'development#dev_login'
  end
end

app/models/service_form.rb
class ServiceForm
  include ActiveModel::Model

  attr_reader :service_name, :service_is_out_of_hours_support_provided

  validates :service_name,
            presence: true,
            length: { maximum: 256 }

  validates :service_is_out_of_hours_support_provided,
            presence: true,
            inclusion: { in: %w[true false] }

  validates_format_of :service_name,
                      with: AwsTagValueValidator.allowed_chars_regexp,
                      message: AwsTagValueValidator.allowed_chars_message

  def initialize(hash)
    params = hash.with_indifferent_access
    @service_name = params[:service_name]
    @service_is_out_of_hours_support_provided = params[:service_is_out_of_hours_support_provided]
  end
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
  def service
    @form = ServiceForm.new(session.fetch('form', {}))
  end

  def post
    form_params = params.fetch(
      'service_form',
      {}
    ).permit(
      :service_name,
      :service_is_out_of_hours_support_provided
    ).to_h
    @form = ServiceForm.new(form_params)
    return render :service if @form.invalid?

    session['form'] = session.fetch('form', {}).merge form_params

    redirect_to @form.service_is_out_of_hours_support_provided == 'true' ?
      out_of_hours_support_path :
      security_path
  end
end

app/views/service/service.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <a href="<%= team_path %>" class="govuk-back-link">Back</a>
    <h1 class="govuk-heading-l">Service details</h1>
    <%= error_summary_for(@form&.errors, :service_form) %>
    <%= form_for @form, url: service_path, html: { novalidate: true } do |f| %>
      <fieldset class="govuk-fieldset">
        <div class="govuk-form-group <%= 'govuk-form-group--error' if @form.errors.include?(:service_name) %>">
          <%= f.label :service_name, 'Service name', class: 'govuk-label govuk-label--m' %>
          <span class="govuk-hint">
            This is like GOV.UK, or EIDAS (in the context of verify)
          </span>
          <%= error_message_on(f.object.errors, :service_name) %>
          <%= f.text_field(
            :service_name,
            value: @form.service_name,
            required: true,
            class: "govuk-input govuk-input--width-20 #{@form.errors&.any? ? 'govuk-textarea--error' : ''}"
          ) %>
        </div>
      </fieldset>
      <fieldset class="govuk-fieldset">
        <div class="govuk-form-group <%= 'govuk-form-group--error' if @form.errors.include?(:service_is_out_of_hours_support_provided) %>">
          <legend class="govuk-fieldset__legend govuk-fieldset__legend--m">
            <h1 class="govuk-fieldset__heading">
              Is out of hours support provided?
            </h1>
          </legend>
          <span class="govuk-hint">
            Select yes if there is a group or individual which would
            respond to issues relating to this account, out of normal
            working hours.
          </span>
          <%= error_message_on(f.object.errors, :service_is_out_of_hours_support_provided) %>

          <div class="govuk-radios govuk-radios--inline">
            <div class="govuk-radios__item">
              <%= f.radio_button(
                :service_is_out_of_hours_support_provided,
                true,
                class: "govuk-radios__input"
              ) %>
              <%= f.label(
                :service_is_out_of_hours_support_provided_true,
                'Yes',
                class: 'govuk-label govuk-radios__label'
              ) %>
            </div>
            <div class="govuk-radios__item">
              <%= f.radio_button(
                :service_is_out_of_hours_support_provided,
                false,
                class: "govuk-radios__input"
              ) %>
              <%= f.label(
                :service_is_out_of_hours_support_provided_false,
                'No',
                class: 'govuk-label govuk-radios__label'
              ) %>
            </div>
          </div>
        </div>
      </fieldset>

      <%= f.submit 'Next', class: 'govuk-button', data: { module: "govuk-button" } %>
    <% end %>
  </div>
</div>