config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'index#index', as: :index
  post '/', to: 'index#post'

  get '/account-details', to: 'account_details#account_details', as: :account_details
  post '/account-details', to: 'account_details#post'

  get '/organisation', to: 'organisation#organisation', as: :organisation
  post '/organisation', to: 'organisation#post'
  
  get '/organisation_summary', to: 'organisation_summary#organisation_summary', as: :organisation_summary
  post '/organisation_summary', to: 'organisation_summary#post'

  get '/team', to: 'team#team', as: :team
  post '/team', to: 'team#post'

  get '/service', to: 'service#service', as: :service
  post '/service', to: 'service#post'

  get '/out-of-hours-support', to: 'out_of_hours_support#out_of_hours_support', as: :out_of_hours_support
  post '/out-of-hours-support', to: 'out_of_hours_support#post'

  get '/security', to: 'security#security', as: :security
  post '/security', to: 'security#post'

  get '/administrators', to: 'administrators#administrators', as: :administrators
  post '/administrators', to: 'administrators#post'

  get '/check-your-answers', to: 'check_your_answers#check_your_answers', as: :check_your_answers
  post '/check-your-answers', to: 'check_your_answers#post'

  get '/confirmation/account', to: 'confirmation#account', as: :confirmation_account

  get '/auth/google_oauth2/callback', to: 'google_auth#callback'
  get '/auth/google_oauth2/error/bad-email', to: 'google_auth#error_bad_email', as: :error_bad_email

  if Rails.env.development?
    get '/dev-login' => 'development#dev_login'
  end
end

app/models/out_of_hours_support_form.rb
class OutOfHoursSupportForm
  include ActiveModel::Model

  attr_reader :out_of_hours_support_contact_name,
              :out_of_hours_support_phone_number,
              :out_of_hours_support_pagerduty_link,
              :out_of_hours_support_email_address

  validates :out_of_hours_support_phone_number,
            presence: true,
            length: { maximum: 256 }

  validates :out_of_hours_support_contact_name,
            :out_of_hours_support_pagerduty_link,
            :out_of_hours_support_email_address,
            length: { maximum: 256 }

  validates_format_of :out_of_hours_support_contact_name,
                      :out_of_hours_support_phone_number,
                      :out_of_hours_support_pagerduty_link,
                      :out_of_hours_support_email_address,
                      with: AwsTagValueValidator.allowed_chars_regexp,
                      message: AwsTagValueValidator.allowed_chars_message

  def initialize(hash)
    params = hash.with_indifferent_access
    @out_of_hours_support_contact_name = params[:out_of_hours_support_contact_name]
    @out_of_hours_support_phone_number = params[:out_of_hours_support_phone_number]
    @out_of_hours_support_pagerduty_link = params[:out_of_hours_support_pagerduty_link]
    @out_of_hours_support_email_address = params[:out_of_hours_support_email_address]
  end
end

app/controllers/out_of_hours_support_controller.rb
class OutOfHoursSupportController < ApplicationController
  def out_of_hours_support
    @form = OutOfHoursSupportForm.new(session.fetch('form', {}))
  end

  def post
    form_params = params.fetch(
      'out_of_hours_support_form',
      {}
    ).permit(
      :out_of_hours_support_contact_name,
      :out_of_hours_support_phone_number,
      :out_of_hours_support_pagerduty_link,
      :out_of_hours_support_email_address
    ).to_h

    @form = OutOfHoursSupportForm.new(form_params)
    return render :out_of_hours_support if @form.invalid?

    session['form'] = session.fetch('form', {}).merge form_params

    redirect_to security_path
  end
end

app/views/out_of_hours_support/out_of_hours_support.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <a href="<%= service_path %>" class="govuk-back-link">Back</a>
    <h1 class="govuk-heading-l">Out of hours support details</h1>
    <%= error_summary_for(@form&.errors, :out_of_hours_support_form) %>
    <%= form_for @form, url: out_of_hours_support_path, html: { novalidate: true } do |f| %>
      <fieldset class="govuk-fieldset">
        <div class="govuk-form-group <%= 'govuk-form-group--error' if @form.errors.include?(:out_of_hours_support_contact_name) %>">
          <%= f.label(
            :out_of_hours_support_contact_name,
            'Responsible person or group (optional)',
            class: 'govuk-label govuk-label--m'
          ) %>
          <span class="govuk-hint">
            This could be an individual, or the name of a group. Leave
            blank if this isn't applicable.
          </span>
          <%= error_message_on(f.object.errors, :out_of_hours_support_contact_name) %>
          <%= f.text_field(
            :out_of_hours_support_contact_name,
            value: @form.out_of_hours_support_contact_name,
            class: "govuk-input govuk-input--width-20"
          ) %>
        </div>
      </fieldset>
      <fieldset class="govuk-fieldset">
        <%= f.label(
          :out_of_hours_support_email_address,
          'Contact details',
          class: 'govuk-label govuk-label--m'
        ) %>
        <div class="govuk-form-group <%= 'govuk-form-group--error' if @form.errors.include?(:out_of_hours_support_phone_number) %>">
          <%= f.label :out_of_hours_support_phone_number, 'Phone number', class: 'govuk-label' %>
          <%= error_message_on(f.object.errors, :out_of_hours_support_phone_number) %>
          <%= f.text_field(
            :out_of_hours_support_phone_number, value: @form.out_of_hours_support_phone_number,
            required: true,
            class: "govuk-input govuk-input--width-20 #{@form.errors.include?(:out_of_hours_support_phone_number) ? 'govuk-input--error' : ''}",
            type: "tel",
            autocomplete: "tel"
          ) %>
        </div>
        <div class="govuk-form-group">
          <%= f.label :out_of_hours_support_pagerduty_link, 'PagerDuty link', class: 'govuk-label' %>
          <%= error_message_on(f.object.errors, :out_of_hours_support_pagerduty_link) %>
          <%= f.text_field(
            :out_of_hours_support_pagerduty_link, value: @form.out_of_hours_support_pagerduty_link,
            class: "govuk-input govuk-input--width-20"
          ) %>
        </div>
        <div class="govuk-form-group">
          <%= f.label :out_of_hours_support_email_address, 'Email address', class: 'govuk-label' %>
          <span class="govuk-hint">
            This may be a shared inbox or mailing list.
          </span>
          <%= error_message_on(f.object.errors, :out_of_hours_support_email_address) %>
          <%= f.text_field(
            :out_of_hours_support_email_address, value: @form.out_of_hours_support_email_address,
            class: "govuk-input govuk-input--width-20"
          ) %>
        </div>
      </fieldset>

      <%= f.submit 'Next', class: 'govuk-button', data: { module: "govuk-button" } %>
    <% end %>
  </div>
</div>